### ISSUE TITLE
Crashing in the Nether.

### ISSUE THREAD

**Issue by Mysteriaa** [NoComment1105/SmoothBedrock-by-Blayyke#1]
### Version
> [1.17] v1.0.2 

### Reproduction Steps

> Enter Nether, generate new chunks

### Crash Report File
[crash-2021-07-15_11.25.27-server.txt](https://github.com/NoComment1105/SmoothBedrock-by-Blayyke/files/6824391/crash-2021-07-15_11.25.27-server.txt)

**Comment by NoComment1105** [comment]
I see you have a large list of mods, could you do a test with smooth bedrock only please?

**Comment by Mysteriaa** [comment]
I use Not Enough Crashes, it immediately blamed this mod for the crash. I tried loading the world with smooth bedrock only anyway however and couldn't because of a world error preventing me from actually opening the world ('safe mode' does nothing, i also do not have any datapacks installed)  
![image](https://user-images.githubusercontent.com/67705660/125817520-d473a3b1-abc5-4669-84ec-8326615afffe.png)

**Comment by NoComment1105** [comment]
Okay, thank you. I'll look into this ASAP, I'm not home currently. Thanks for the report

**Comment by NoComment1105** [comment]
After doing some testing, i can confirm this mod is not a fault, the nether works fine on my machine. I'm going to assume that this is a mod conflict. If you want to try and whittle down the conflict, that would be ideal seeing as my time is too limited to cipher through your extensive mod list. Thanks for the report
